# Generated by Django 5.2.2 on 2025-06-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер'),
        ),
    ]
