# Generated by Django 5.2.2 on 2025-06-15 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('shop', '0002_alter_subcategorymodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productmodel', verbose_name='Продукт'),
        ),
    ]
