# Generated by Django 5.2.2 on 2025-06-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='requires',
            field=models.BooleanField(default=False, verbose_name='Требуется доставка'),
        ),
    ]
