# Generated by Django 5.2.2 on 2025-06-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_ordermodel_requires'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderitem',
            managers=[
            ],
        ),
    ]
